import type { MerchantCatalogEntry } from "./types";

export const MERCHANT_CATALOG: MerchantCatalogEntry[] = [
  {
    slug: "netflix",
    name: "Netflix",
    iconSlug: "netflix",
    aliases: ["netflix", "nflx"],
  },
  {
    slug: "spotify",
    name: "Spotify",
    iconSlug: "spotify",
    aliases: ["spotify"],
  },
  {
    slug: "hbo-max",
    name: "HBO Max",
    iconSlug: "hbomax",
    aliases: ["hbo max", "hbomax", "hbo"],
  },
  {
    slug: "max",
    name: "Max",
    iconSlug: "max",
    aliases: ["max streaming", "warner max"],
  },
  {
    slug: "paramount-plus",
    name: "Paramount+",
    iconSlug: "paramountplus",
    aliases: ["paramount plus", "paramountplus", "paramount"],
  },
  {
    slug: "apple-music",
    name: "Apple Music",
    iconSlug: "applemusic",
    aliases: ["apple music"],
  },
  {
    slug: "apple-tv",
    name: "Apple TV+",
    iconSlug: "appletv",
    aliases: ["apple tv", "appletv", "apple tv plus"],
  },
  {
    slug: "icloud",
    name: "iCloud",
    iconSlug: "icloud",
    aliases: ["icloud", "icloud storage", "icloud+"],
  },
  {
    slug: "apple",
    name: "Apple",
    iconSlug: "apple",
    aliases: ["apple one", "apple services"],
  },
  {
    slug: "youtube",
    name: "YouTube",
    iconSlug: "youtube",
    aliases: ["youtube premium", "youtube"],
  },
  {
    slug: "youtube-music",
    name: "YouTube Music",
    iconSlug: "youtubemusic",
    aliases: ["youtube music", "yt music"],
  },
  {
    slug: "google",
    name: "Google",
    iconSlug: "google",
    aliases: ["google one", "google workspace", "google storage"],
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    iconSlug: "googledrive",
    aliases: ["google drive", "googledrive"],
  },
  {
    slug: "github",
    name: "GitHub",
    iconSlug: "github",
    aliases: ["github"],
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    iconSlug: "githubcopilot",
    aliases: ["github copilot", "copilot"],
  },
  {
    slug: "notion",
    name: "Notion",
    iconSlug: "notion",
    aliases: ["notion"],
  },
  {
    slug: "figma",
    name: "Figma",
    iconSlug: "figma",
    aliases: ["figma"],
  },
  {
    slug: "playstation",
    name: "PlayStation",
    iconSlug: "playstation",
    aliases: ["playstation", "playstation plus", "ps plus", "psn"],
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    iconSlug: "dropbox",
    aliases: ["dropbox"],
  },
  {
    slug: "duolingo",
    name: "Duolingo",
    iconSlug: "duolingo",
    aliases: ["duolingo"],
  },
  {
    slug: "nordvpn",
    name: "NordVPN",
    iconSlug: "nordvpn",
    aliases: ["nordvpn", "nord vpn"],
  },
  {
    slug: "proton-vpn",
    name: "Proton VPN",
    iconSlug: "protonvpn",
    aliases: ["proton vpn", "protonvpn"],
  },
  {
    slug: "expressvpn",
    name: "ExpressVPN",
    iconSlug: "expressvpn",
    aliases: ["expressvpn", "express vpn"],
  },
  {
    slug: "surfshark",
    name: "Surfshark",
    iconSlug: "surfshark",
    aliases: ["surfshark"],
  },
  {
    slug: "twitch",
    name: "Twitch",
    iconSlug: "twitch",
    aliases: ["twitch"],
  },
  {
    slug: "crunchyroll",
    name: "Crunchyroll",
    iconSlug: "crunchyroll",
    aliases: ["crunchyroll"],
  },
  {
    slug: "deezer",
    name: "Deezer",
    iconSlug: "deezer",
    aliases: ["deezer"],
  },
  {
    slug: "tidal",
    name: "Tidal",
    iconSlug: "tidal",
    aliases: ["tidal"],
  },
  {
    slug: "soundcloud",
    name: "SoundCloud",
    iconSlug: "soundcloud",
    aliases: ["soundcloud"],
  },
  {
    slug: "strava",
    name: "Strava",
    iconSlug: "strava",
    aliases: ["strava"],
  },
  {
    slug: "peloton",
    name: "Peloton",
    iconSlug: "peloton",
    aliases: ["peloton"],
  },
  {
    slug: "audible",
    name: "Audible",
    iconSlug: "audible",
    aliases: ["audible"],
  },
  {
    slug: "vodafone",
    name: "Vodafone",
    iconSlug: "vodafone",
    aliases: ["vodafone"],
  },
  {
    slug: "movistar",
    name: "Movistar",
    iconSlug: "movistar",
    aliases: ["movistar"],
  },
  {
    slug: "orange",
    name: "Orange",
    iconSlug: "orange",
    aliases: ["orange"],
  },
  {
    slug: "deepl",
    name: "DeepL",
    iconSlug: "deepl",
    aliases: ["deepl"],
  },
  {
    slug: "1password",
    name: "1Password",
    iconSlug: "1password",
    aliases: ["1password", "1 password"],
  },
  {
    slug: "bitwarden",
    name: "Bitwarden",
    iconSlug: "bitwarden",
    aliases: ["bitwarden"],
  },
  {
    slug: "proton-mail",
    name: "Proton Mail",
    iconSlug: "protonmail",
    aliases: ["proton mail", "protonmail"],
  },
  {
    slug: "cursor",
    name: "Cursor",
    iconSlug: "cursor",
    aliases: ["cursor"],
  },
  {
    slug: "vercel",
    name: "Vercel",
    iconSlug: "vercel",
    aliases: ["vercel"],
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    iconSlug: "cloudflare",
    aliases: ["cloudflare"],
  },
];
